# Generated by Django 5.0 on 2023-12-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_aknowledjment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expected_deliverydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
