# Generated by Django 5.0 on 2023-12-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_average_response_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfomance',
            old_name='on_time_delivery_date',
            new_name='on_time_delivery_rate',
        ),
    ]
