# Generated by Django 5.0 on 2023-12-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_rename_on_time_delivery_date_perfomance_on_time_delivery_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomance',
            name='average_respose_time',
        ),
        migrations.AddField(
            model_name='perfomance',
            name='average_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='perfomance',
            name='fulfilment_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='perfomance',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='perfomance',
            name='quality_rating_avg',
            field=models.FloatField(default=0),
        ),
    ]
